### ISSUE TITLE
Change recipes for Minecraft 1.12.2

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/vegcraft#1]
Hey @ACascarino , thanks for making VegCraft! It's really awesome! I literally had the same idea this past weekend and was delighted to see someone out there beat me to it. :-)

With this fork of mine, I hope to make the mod accessible for Minecraft 1.12.2 for when data packs did not exist yet (support for those came in 1.13). No action is needed on your end, I just wanted to make you aware of my plans. If applicable, I would be happy to upstream new recipes into your data pack as well!

I want to import these recipes into a Forge mod for Minecraft 1.12.2. It is the last release to have the largest amount of supported mods and I currently have a long-running server on that version of Minecraft with over 100 mods installed.

Short-term, the [Uncrafted](https://www.curseforge.com/minecraft/mc-mods/uncrafted) mod I use has great synergy with this. It (1) allows almost everything to be crafted from scratch from vanilla Minecraft and (2) it dynamically loads new recipes and the developer even encourages users to add their own. But it lacks recipes for feathers, ink sacs, and other items. I will update the recipes in this git repository and will only re-build Uncrafted for private use since their licensing is unclear.

Long-term, I want to transform this fork of VegCraft into a standalone Forge mod for Minecraft 1.12.2. That is something I can distribute in the future on [Curse Forge](https://www.curseforge.com/minecraft/mc-mods). I will link to your data pack for users on versions of Minecraft that are newer than 1.12.2.

**Comment by LukeShortCloud** [comment]
Copying the recipes straight into the Uncrafted mod and loading it results a handful of issues that need to be addressed. These issues can be summarized as:

- Content that does not exist in Minecraft 1.12:
    - Recipe type devices from Minecraft 1.14 such as a smoker.
    - Dyes have been renamed or are missing entirely. For example, ["Cactus Green" has been renamed to "Green Dye"](https://minecraft.fandom.com/wiki/Green_Dye) in Minecraft 1.13.
    - Honey was added in [Minecraft 1.14](https://minecraft.fandom.com/wiki/Honey_Bottle).
        - We can switch to apples since, in real life, applesauce is a great baking replacement.
        - We also need to remove the honey recipe.

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:string_seagrass
com.google.gson.JsonSyntaxException: Unknown recipe type: minecraft:smelting
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:string_grass
com.google.gson.JsonSyntaxException: Unknown recipe type: minecraft:smelting
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:rotten_flesh_potato
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:green_dye'
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:rotten_flesh_apple
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:green_dye'
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:pumpkin_pie
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:honey_bottle'
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:honey_bottle_rot90
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:orange_dye'
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:honey_bottle
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:orange_dye'
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:gunpowder
com.google.gson.JsonParseException: Missing data for item 'minecraft:coal'
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:ender_pearl_smoked
com.google.gson.JsonSyntaxException: Unknown recipe type: minecraft:smoking
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:ender_pearl
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:cyan_dye'
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:cake
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:honey_bottle'
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:book_and_quill
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:black_dye'
```

```
[11:10:17] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:black_dye
com.google.gson.JsonSyntaxException: Unknown recipe type: minecraft:stonecutting
```

**Comment by LukeShortCloud** [comment]
All recipes have been imported and/or modified to work with Minecraft 1.12.2. We have our first release up (0.1.0) with the changes.

**Comment by ACascarino** [comment]
Hi @LukeShortCloud,
Absolutely delighted someone else has found this useful! VegCraft was mainly put together for personal/friends' use on a group server so I'm really glad it's making an impact elsewhere. Very supportive of any extension and/or ideas you may have going forward.

It's noteworthy that not a huge number of these proposed recipes are playtested in a starting-from-zero survival world - when I developed this pack our server was already pretty much post-scarcity so finding the requisite ingredients wasn't an issue. I'd be interested in hearing any ideas/observations around balance and relative cost for each of these items as your development process matures!

In addition, I'm aware there are still a number of items I've yet to port, at least for the version of MC I was developing these for (Java 1.16) - Spider Eyes jump out at me as one of the major ones. If you've ideas on recipes for these missing items, absolutely let me know and I'd love to have them upstreamed, or we can work out if there's a process in post-1.12 that can suit them.

I do absolutely intend on actually finishing the pack in the short term, but I'm a little unwell at the present moment so it'll probably be a couple of weeks before I can commit to actually implementing the rest of the recipes.

Finally, I generated the images for the crafting recipes by using the Minecraft Wiki's templating system; you can find the wiki page I used to generate them [here](https://minecraft.fandom.com/wiki/User:ACascarino/vegcraft).

**Comment by LukeShortCloud** [comment]
That is the beauty of open source, being able to share and collaborate. I love it! Thanks for sharing your data pack, I'm now essentially using it with my friends. :-)

I'm also in a similar situation. My friends and I are already late-game and I have no plans on starting a new server. After many years of testing hundreds of Forge mods, we've settled on the best ones. Even upgrading Minecraft is not an option since most of these mods (especially the best ones like Galacticraft [you can explore the entire solar system!]) do not have newer versions available. I may take some time to test these out in a single player world. I do wonder about balance, too. The rotten flesh recipes, for example, make a lot of sense and are also very involved.

My ultimate goal is to align our fork with your original project as much as possible. As I keep finding out, there are a handful of differences between Minecraft 1.12 and 1.13 or newer. Even still, I feel that we can both work together to finish this up. Spider eyes and all! And thanks for your tip about the image generation, that is very useful!
