### ISSUE TITLE
Fix Ender Pearl recipes

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/vegcraft#13]
There are two issues.

1. The smoker does not exist in Minecraft 1.12:

```
[18:22:16] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:ender_pearl_smoked
com.google.gson.JsonSyntaxException: Unknown recipe type: minecraft:smoking
```

2. The cyan dye is the item "minecraft:dye" with data value "6". https://minecraft-ids.grahamedgecombe.com/

```
[18:22:16] [Client thread/ERROR] [FML]: Parsing error loading recipe uncrafted:ender_pearl
com.google.gson.JsonSyntaxException: Unknown item 'minecraft:cyan_dye'
```

Related: https://github.com/LukeShortCloud/vegcraft/issues/1

**Comment by LukeShortCloud** [comment]
The crafting picture on VegCraft suggests that (for the end game recipe that is easier to make), it requires smelting Endstone to make an Ender Pearl. However, the real [ender_pearl_smoked.json](https://github.com/ACascarino/vegcraft/blob/446dc01ff4874667b9918a837446003e9a271aa2/data/vegcraft/recipes/ender_pearl_smoked.json) recipe requires a Chorus Fruit in a Smoker. We cannot currently use a furnace for simplicity sake and the smoker does not exist yet. I do like the idea of using chorus fruit somehow. Remember, this recipe should be simpler than the first one (which is 7x Nether Quartz, 1x Cyan Dye, and 1x Bottle o' Enchanting).

Possible recipe (that provides 3x): Chorus Fruit, Glass Pane, Gunpowder, Cyan Dye

**Comment by ACascarino** [comment]
Apologies - I think I must have made an undocumented change from smithing End Stone to smoking Chorus Fruit. Good job me; lesson learnt, document your changes...

**Comment by LukeShortCloud** [comment]
No worries! I figured it out after a few minutes of investigation.

Long-term, once I figure out smelting recipes in Minecraft 1.12 (it requires writing actual Java code), I'd like to keep our recipes more consistent with yours by just replacing smoker recipes with furnace recipes.
