### ISSUE TITLE
Add ink sac recipe

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/vegcraft#6]
This is useful for some vanilla Minecraft recipes and also a few modded ones as well. For example, JurassiCraft requires an ink sac to craft tires for cars and helicopters.

**Comment by LukeShortCloud** [comment]
The original VegCraft relied on using black dye instead of ink sacs for a few recipes. Two problems we are facing in modded 1.12: (1) black dye does not exist in vanilla Minecraft 1.12 and (2) modded recipes may need ink sacs.

Related: https://github.com/LukeShortCloud/vegcraft/issues/4

**Comment by ACascarino** [comment]
Interesting observation about other modded packs requiring the use of ink sacs - I'd not really considered that. I wonder whether there's something I can do in my 1.16 version that always forces the two to be equivalent. If nothing else creating a recipe that allows for black dye -> ink sac would be inelegant but functional.

**Comment by LukeShortCloud** [comment]
It appears that black dye can be created from two items in newer version of Minecraft: (1) Ink Sac or (2) Wither Rose. If a Black Dye can become an Ink Sac then technically someone could go from Wither Rose -> Black Dye -> Ink Sac. The Wither Rose was not added until Minecraft 1.14. [2] That would have been the only vegan way to get Black Dye. In Minecraft 1.12, the Ink Sac is directly used as the dye.

"A black dye can be obtained using an Ink Sac or a Wither Rose, both of which result in one black dye." [2]

1. https://www.sportskeeda.com/minecraft/top-5-uses-wither-roses-minecraft#:~:text=Wither%20Rose%20was%20added%20to,it%20drops%20one%20Wither%20Rose.
2. https://minecraft-archive.fandom.com/wiki/Black_Dye#:~:text=Obtaining,result%20in%20one%20black%20dye.

I just added a recipe yesterday for Ink Sac to be: Charcoal + Watter Bottle. Here are other alternatives I considered with the goal to simulate the sac/pouch/ink jar (when making a Book and Quill the ink sac magically becomes an ink jar lol):

- Charcoal + Leather
- Charcoal + Leather + Water Bottle
- Charcoal + Rotten Flesh
- Charcoal + Rotten Flesh + Water Bottle
- Charcoal + Water Bucket
- Charcoal

Let me know what you think. Would love to keep our fork of your mod as consistent as possible.

**Comment by ACascarino** [comment]
Hmm!
I like Charcoal + Water Bottle - I think it's the closest we're going to get to the idea of black dye for a version that doesn't include it. Mulling it over, I'd also be happy to just include this in the upstream as-is - this means that the recipe is consistent between versions, but there becomes a more efficient way of doing it in later versions once the stonemason exists.
